language: go

go:
 - 1.8.1


cache:
  directories:
    - "$HOME/google-cloud-sdk/"

# Unconditionally place the repo at GOPATH/src/${go_import_path} to support
# forks.
go_import_path: github.com/m-lab/prometheus-support

install:
  # Install promtool and pin it at the latest stable version, currently 1.8.0
- PROMTOOL_URI=github.com/prometheus/prometheus/cmd/promtool;
  PROMTOOL_VERSION=1.8.0;
  go get -d $PROMTOOL_URI;
  git -C $GOPATH/src/$PROMTOOL_URI
  checkout -b $PROMTOOL_VERSION tags/v$PROMTOOL_VERSION;
  go install $PROMTOOL_URI
  # Install kexpand templating tool, version 0.2.
- KEXPAND_URI=github.com/kopeio/kexpand;
  KEXPAND_VERSION=0.2;
  go get -d $KEXPAND_URI;
  git -C $GOPATH/src/$KEXPAND_URI checkout 0.2;
  make
- $TRAVIS_BUILD_DIR/travis/install_gcloud.sh kubectl

script:
# Run query "unit tests".
- go test -v github.com/m-lab/prometheus-support/cmd/query_tester -args -log.level warn

# Use promtool to check current alerts and rules. This is only a syntax check.
- promtool check-rules config/federation/prometheus/alerts.yml
- promtool check-rules config/federation/prometheus/rules.yml

# TODO(soltesz): support check-config.
# promtool check-config config/federation/prometheus/prometheus.yml
# promtool check-config config/cluster/prometheus/prometheus.yml

deploy:
#########################################
## Sandbox
- provider: script
  script: $TRAVIS_BUILD_DIR/kubectl.sh mlab-sandbox prometheus-federation ./apply-global-prometheus.sh
  skip_cleanup: true
  on:
    repo: m-lab/prometheus-support
    all_branches: true
    condition: $TRAVIS_BRANCH == sandbox-* && $TRAVIS_EVENT_TYPE == push

- provider: script
  script: $TRAVIS_BUILD_DIR/kubectl.sh mlab-sandbox scraper-cluster ./apply-cluster.sh
  skip_cleanup: true
  on:
    repo: m-lab/prometheus-support
    all_branches: true
    condition: $TRAVIS_BRANCH == sandbox-* && $TRAVIS_EVENT_TYPE == push

- provider: script
  script: $TRAVIS_BUILD_DIR/kubectl.sh mlab-sandbox downloader ./apply-cluster.sh
  skip_cleanup: true
  on:
    repo: m-lab/prometheus-support
    all_branches: true
    condition: $TRAVIS_BRANCH == sandbox-* && $TRAVIS_EVENT_TYPE == push

#########################################
## Staging
- provider: script
  script: $TRAVIS_BUILD_DIR/kubectl.sh mlab-staging prometheus-federation ./apply-global-prometheus.sh
  skip_cleanup: true
  on:
    repo: m-lab/prometheus-support
    all_branches: true
    condition: $TRAVIS_BRANCH == master && $TRAVIS_EVENT_TYPE == push

- provider: script
  script: $TRAVIS_BUILD_DIR/kubectl.sh mlab-staging scraper-cluster ./apply-cluster.sh
  skip_cleanup: true
  on:
    repo: m-lab/prometheus-support
    all_branches: true
    condition: $TRAVIS_BRANCH == master && $TRAVIS_EVENT_TYPE == push

- provider: script
  script: $TRAVIS_BUILD_DIR/kubectl.sh mlab-staging downloader ./apply-cluster.sh
  skip_cleanup: true
  on:
    repo: m-lab/prometheus-support
    all_branches: true
    condition: $TRAVIS_BRANCH == master && $TRAVIS_EVENT_TYPE == push

#########################################
## Production
# TODO: enforce a format on the $TRAVIS_TAG name.
- provider: script
  script: $TRAVIS_BUILD_DIR/kubectl.sh mlab-oti prometheus-federation ./apply-global-prometheus.sh
  skip_cleanup: true
  on:
    repo: m-lab/prometheus-support
    tags: true

- provider: script
  script: $TRAVIS_BUILD_DIR/kubectl.sh mlab-oti scraper-cluster ./apply-cluster.sh
  skip_cleanup: true
  on:
    repo: m-lab/prometheus-support
    tags: true

- provider: script
  script: $TRAVIS_BUILD_DIR/kubectl.sh mlab-oti downloader ./apply-cluster.sh
  skip_cleanup: true
  on:
    repo: m-lab/prometheus-support
    tags: true


before_install:
- travis/decrypt.sh "$encrypted_1c8dd3704323_key" "$encrypted_1c8dd3704323_iv"
  keys/service-accounts.tar.enc /tmp/service-accounts.tar /tmp
