apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      # Used to match pre-existing pods that may be affected during updates.
      run: prometheus-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  # Pod template.
  template:
    metadata:
      labels:
        # Note: run=prometheus-server should match a service config with a
        # public IP and port so that it is publically accessible.
        run: prometheus-server
    spec:
      containers:
      - image: measurementlab/prometheus-server:v1.5.2-1
        # Note: this value appears to be ignored and the actual pod name is
        # derived from the Deployment.metadata.name. However, removing this
        # value results in a configuration error.
        name: prometheus-server
        ports:
          - containerPort: 9090
        resources:
          requests:
            memory: "3Gi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /prometheus
          name: prometheus-storage
      # Disks created manually, can be named here explicitly using
      # gcePersistentDisk instead of the persistentVolumeClaim.
      volumes:
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: auto-prometheus-disk0
