# M-Lab Prometheus configuration.

# global:
  # scrape_interval:     60s  # Set the scrape interval to every 60 seconds.
  # evaluation_interval: 60s  # Evaluate rules every 60 seconds.
  # scrape_timeout is set to the global default (10s).

  # These labels are attached to any time series or alert sent to external
  # systems (federation, remote storage, Alertmanager).
  # TODO(soltesz): use this when M-Lab adds federation or alertmanager.
  # external_labels:
  #   monitor: 'mlab1'
