groups:
- name: rules.yml
  rules:
  - record: ipv4_and_ipv6:sidestream_connection_count:increase2m
    expr: increase(sidestream_connection_count{type=~"ipv4|ipv6"}[2m])
  - record: instance:sidestream_connection_count:increase2m
    expr: sum by(instance) (increase(sidestream_connection_count{type=~"ipv4|ipv6"}[2m]))
  - record: lsb:sidestream_connection_count:increase2m
    expr: sum by(lsb) (increase(sidestream_connection_count{type=~"ipv4|ipv6"}[2m]))
  - record: machine:inotify_extension_create:rpm2m
    expr: 60 * sum without(ext) (irate(inotify_extension_create_total{ext=~".*_snaplog"}[4m]))
  - record: switch:ifHCOutOctets:bps2m
    expr: 8 * irate(ifHCOutOctets{ifAlias="uplink"}[4m])
  - record: machine:node_disk_io_time_ms:max_ratio2m
    expr: max without(device) (irate(node_disk_io_time_ms{service="nodeexporter"}[4m]))
      / 1000
  - record: ndt:vdlimit_used:predict_linear3h_12h
    expr: predict_linear(vdlimit_used{experiment="ndt.iupui"}[3h], 12 * 60 * 60)
  - record: switch:jnxCosQstatTotalDropPkts:irate4m_gt_0
    expr: irate(jnxCosQstatTotalDropPkts{ifAlias="uplink",qNumber="0"}[4m]) > 0
  - record: switch:jnxCosQstatTotalDropPkts:irate4m
    expr: irate(jnxCosQstatTotalDropPkts{ifAlias="uplink",qNumber="0"}[4m])
  - record: switch:ifOutDiscards:irate4m_gt_0
    expr: irate(ifOutDiscards{ifAlias="uplink"}[4m]) > 0
  - record: switch:ifOutDiscards:irate4m
    expr: irate(ifOutDiscards{ifAlias="uplink"}[4m])
  - record: candidate_site:uplink:90th_quantile_30m
    expr: quantile_over_time(0.9, switch:ifHCOutOctets:bps2m{ifAlias="uplink"}[30m])
  - record: candidate_machine:inotify_extension_create_rpm:90th_quantile_30m
    expr: quantile_over_time(0.9, machine:inotify_extension_create:rpm2m[30m])
  - record: candidate_machine:node_disk_io_time_ratio:90th_quantile_30m
    expr: quantile_over_time(0.9, machine:node_disk_io_time_ms:max_ratio2m[30m])
  - record: candidate_ndt:vdlimit_used_12h_prediction:90th_quantile_30m
    expr: quantile_over_time(0.9, ndt:vdlimit_used:predict_linear3h_12h[30m])
  - record: candidate_site:uplink:90th_quantile_1h
    expr: quantile_over_time(0.9, switch:ifHCOutOctets:bps2m{ifAlias="uplink"}[1h])
  - record: candidate_machine:inotify_extension_create_rpm:90th_quantile_1h
    expr: quantile_over_time(0.9, machine:inotify_extension_create:rpm2m[1h])
  - record: candidate_machine:node_disk_io_time_ratio:90th_quantile_1h
    expr: quantile_over_time(0.9, machine:node_disk_io_time_ms:max_ratio2m[1h])
  - record: candidate_ndt:vdlimit_used_12h_prediction:90th_quantile_1h
    expr: quantile_over_time(0.9, ndt:vdlimit_used:predict_linear3h_12h[1h])
  - record: candidate_site:uplink:90th_quantile_2h
    expr: quantile_over_time(0.9, switch:ifHCOutOctets:bps2m{ifAlias="uplink"}[2h])
  - record: candidate_machine:inotify_extension_create_rpm:90th_quantile_2h
    expr: quantile_over_time(0.9, machine:inotify_extension_create:rpm2m[2h])
  - record: candidate_machine:node_disk_io_time_ratio:90th_quantile_2h
    expr: quantile_over_time(0.9, machine:node_disk_io_time_ms:max_ratio2m[2h])
  - record: candidate_ndt:vdlimit_used_12h_prediction:90th_quantile_2h
    expr: quantile_over_time(0.9, ndt:vdlimit_used:predict_linear3h_12h[2h])
  - record: candidate_site:uplink:90th_quantile_6h
    expr: quantile_over_time(0.9, switch:ifHCOutOctets:bps2m{ifAlias="uplink"}[6h])
  - record: candidate_machine:inotify_extension_create_rpm:90th_quantile_6h
    expr: quantile_over_time(0.9, machine:inotify_extension_create:rpm2m[6h])
  - record: candidate_machine:node_disk_io_time_ratio:90th_quantile_6h
    expr: quantile_over_time(0.9, machine:node_disk_io_time_ms:max_ratio2m[6h])
  - record: candidate_ndt:vdlimit_used_12h_prediction:90th_quantile_6h
    expr: quantile_over_time(0.9, ndt:vdlimit_used:predict_linear3h_12h[6h])
  - record: candidate_site:uplink:98th_quantile_2h
    expr: quantile_over_time(0.98, switch:ifHCOutOctets:bps2m{ifAlias="uplink"}[2h])
  - record: candidate_machine:inotify_extension_create_rpm:98th_quantile_2h
    expr: quantile_over_time(0.98, machine:inotify_extension_create:rpm2m[2h])
  - record: candidate_machine:node_disk_io_time_ratio:98th_quantile_2h
    expr: quantile_over_time(0.98, machine:node_disk_io_time_ms:max_ratio2m[2h])
  - record: candidate_ndt:vdlimit_used_12h_prediction:98th_quantile_2h
    expr: quantile_over_time(0.98, ndt:vdlimit_used:predict_linear3h_12h[2h])
  - record: candidate_site:uplink:98th_quantile_6h
    expr: quantile_over_time(0.98, switch:ifHCOutOctets:bps2m{ifAlias="uplink"}[6h])
  - record: candidate_machine:inotify_extension_create_rpm:98th_quantile_6h
    expr: quantile_over_time(0.98, machine:inotify_extension_create:rpm2m[6h])
  - record: candidate_machine:node_disk_io_time_ratio:98th_quantile_6h
    expr: quantile_over_time(0.98, machine:node_disk_io_time_ms:max_ratio2m[6h])
  - record: candidate_ndt:vdlimit_used_12h_prediction:98th_quantile_6h
    expr: quantile_over_time(0.98, ndt:vdlimit_used:predict_linear3h_12h[6h])
  - record: candidate_site:uplink:gt_500mbps
    expr: switch:ifHCOutOctets:bps2m{ifAlias="uplink"} > bool 5e+08
  - record: candidate_machine:inotify_extension_create_rpm:gt_60
    expr: machine:inotify_extension_create:rpm2m > bool 60
  - record: candidate_machine:node_disk_io_time_ratio:gt_50_pct
    expr: machine:node_disk_io_time_ms:max_ratio2m > bool 0.5
  - record: candidate_ndt:vdlimit_used_12h_prediction:gt_50gb
    expr: ndt:vdlimit_used:predict_linear3h_12h > bool 5e+07
  - record: candidate_service:etl_test_count:increase24h
    expr: sum by(service) (increase(etl_test_count{service!~".*batch.*",status="ok"}[1d]))
