# Configuration values for mlab-oti

GCLOUD_PROJECT: mlab-oti
PROMETHEUS_RAM: 14Gi
PROMETHEUS_CPU: 6000m
PROMETHEUS_VOLUME_SIZE: 400Gi
EXTERNAL_IP: 35.184.81.106
TLS_EMAIL: support@measurementlab.net
TLS_IP: 35.194.63.109
