# Configuration values for mlab-staging

GCLOUD_PROJECT: mlab-staging
PROMETHEUS_HEAP_SIZE: 9000000000
PROMETHEUS_RAM: 18Gi
PROMETHEUS_CPU: 6000m
PROMETHEUS_VOLUME_SIZE: 400Gi
EXTERNAL_IP: 35.185.76.159
TLS_EMAIL: support@measurementlab.net
TLS_IP: 35.196.34.1
GITHUB_RECEIVER_INMEMORY: true
