apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: alertmanager-tls
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: prometheus-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  tls:
  - hosts:
    - alertmanager.{{GCLOUD_PROJECT}}.measurementlab.net
    secretName: alertmanager-tls
  rules:
  - host: alertmanager.{{GCLOUD_PROJECT}}.measurementlab.net
    http:
      paths:
      - path: /
        backend:
          serviceName: alertmanager-tls-service
          servicePort: 9093
