apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-tls
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
  - hosts:
    - {{TLS_DOMAIN}}
    secretName: grafana-tls
  rules:
  - host: {{TLS_DOMAIN}}
    http:
      paths:
      - path: /*
        backend:
          serviceName: grafana-tls-service
          servicePort: 3000
