apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  namespace: nginx-ingress
  labels:
    app: nginx-lb
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: {{TLS_IP}}
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
  selector:
    app: nginx

